name: Update Images

on:
  schedule:
    - cron: '0 0 * * *' # Chạy vào 0h sáng hàng ngày
  workflow_dispatch: # Cho phép bấm nút chạy thủ công để test
  push:
    branches:
      - master
      - main # Thêm main phòng trường hợp bạn dùng branch main

jobs:
  update-images:
    runs-on: ubuntu-latest
    permissions: # Cấp quyền ghi cho bot để commit code
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make bash script executable
      run: chmod +x update_images.bash

    - name: Run update script
      run: ./update_images.bash

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add stats/*
        # Chỉ commit nếu có sự thay đổi
        git diff-index --quiet HEAD || (git commit -m "Update README images" && git push)